/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.authentec.java.ptapi.samples.basicsample;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int ButtonDeleteAll=0x7f05000f;
        public static final int ButtonGrab=0x7f050011;
        public static final int ButtonLeftIndex=0x7f050006;
        public static final int ButtonLeftLittle=0x7f050009;
        public static final int ButtonLeftMiddle=0x7f050007;
        public static final int ButtonLeftRing=0x7f050008;
        public static final int ButtonLeftThumb=0x7f050005;
        public static final int ButtonNavigateDiscrete=0x7f050014;
        public static final int ButtonNavigateMouse=0x7f050013;
        public static final int ButtonNavigateRaw=0x7f050012;
        public static final int ButtonQuit=0x7f050015;
        public static final int ButtonRightIndex=0x7f05000b;
        public static final int ButtonRightLittle=0x7f05000e;
        public static final int ButtonRightMiddle=0x7f05000c;
        public static final int ButtonRightRing=0x7f05000d;
        public static final int ButtonRightThumb=0x7f05000a;
        public static final int ButtonVerifyAll=0x7f050010;
        public static final int EnrollmentLeftLayout=0x7f050004;
        public static final int EnrollmentTextView=0x7f050016;
        public static final int RelativeLayout01=0x7f050002;
        public static final int RelativeLayout02=0x7f050003;
        public static final int img=0x7f050000;
        public static final int pass=0x7f050001;
    }
    public static final class layout {
        public static final int fpdisplay=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int OK=0x7f040013;
        public static final int app_name=0x7f040000;
        public static final int basic_sample=0x7f040001;
        public static final int delete_all=0x7f04000c;
        public static final int grab=0x7f04000e;
        public static final int identify=0x7f04000d;
        public static final int left_index=0x7f040003;
        public static final int left_little=0x7f040006;
        public static final int left_middle=0x7f040004;
        public static final int left_ring=0x7f040005;
        public static final int left_thumb=0x7f040002;
        public static final int navigate_discrete=0x7f040011;
        public static final int navigate_mouse=0x7f040010;
        public static final int navigate_raw=0x7f04000f;
        public static final int quit=0x7f040012;
        public static final int right_index=0x7f040008;
        public static final int right_little=0x7f04000b;
        public static final int right_middle=0x7f040009;
        public static final int right_ring=0x7f04000a;
        public static final int right_thumb=0x7f040007;
    }
}
